### ISSUE TITLE
[BUG] App crashing when logged in and navigating to '/profile' page for first time

### ISSUE THREAD

**Issue by connoro7** [connoro7/console.shop#57]
# Error: TypeError: Cannot read property 'name' of undefined

Getting an error when logging into a user account and navigating the the `/profile` page. Seems to only happen the first time a user navigates to `/profile`, as the error resolves itself upon page reload.

> at src/screens/ProfileScreen.js:32

```diff
  28 useEffect(() => {
  29   if (!userInfo) {
  30     history.push('/login')
  31   } else {
- 32     if (!user.name) {
  33      dispatch(getUserDetails('profile'))
  34    } else {
  35      setName(user.name)
  36      setEmail(user.email)
  37    }
  38  }
  39 }, [dispatch, history, userInfo, user])
```

### Error reproduction:
1. Start server with `npm run dev`
2. Navigate to `/login`
3. Log in with user `admin@example.com` , password `123456`
4. Navigate to `/profile`
5. Bear witness to this terrestrial manifestation of my nightmares
6. Refresh the page at `/profile`
7. **App no longer crashes** -- ***Needs investigation***

**Comment by DavidVainer** [comment]
Change that condition to ```` if (!user?.name) ```` and it should work fine :)

**Comment by connoro7** [comment]
Fixed -- thank you for pointing that out for me!

For those in the ✨far future✨ stumbling upon this ticket and perhaps encountering a similar issue, the difference in `if(!user.name)` and `if(!user?.name)` is the chaining operator `.` and optional chaining operator `?.`.

For the sake of brevity, here's [the MDN reference for optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

Thanks @DavidVainer!
